// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADLCCKVs3W_xZWxWNc7W6dKdqvU-GcLWY',
    appId: '1:809290750100:web:2321fdeaea27e46f46bc81',
    messagingSenderId: '809290750100',
    projectId: 'eprojectbabyshop',
    authDomain: 'eprojectbabyshop.firebaseapp.com',
    storageBucket: 'eprojectbabyshop.firebasestorage.app',
    measurementId: 'G-QS0T9ZGNR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLmmUpbnaNyOzcH-xrZul4kC4uFm0cuHs',
    appId: '1:809290750100:android:a0324dba8b0c013f46bc81',
    messagingSenderId: '809290750100',
    projectId: 'eprojectbabyshop',
    storageBucket: 'eprojectbabyshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2GSmKa0i3UF3syYKDoNGxo90ZiKvx0jE',
    appId: '1:809290750100:ios:6e9e9c382bb973fd46bc81',
    messagingSenderId: '809290750100',
    projectId: 'eprojectbabyshop',
    storageBucket: 'eprojectbabyshop.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2GSmKa0i3UF3syYKDoNGxo90ZiKvx0jE',
    appId: '1:809290750100:ios:6e9e9c382bb973fd46bc81',
    messagingSenderId: '809290750100',
    projectId: 'eprojectbabyshop',
    storageBucket: 'eprojectbabyshop.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADLCCKVs3W_xZWxWNc7W6dKdqvU-GcLWY',
    appId: '1:809290750100:web:84f79cbeb6301d1346bc81',
    messagingSenderId: '809290750100',
    projectId: 'eprojectbabyshop',
    authDomain: 'eprojectbabyshop.firebaseapp.com',
    storageBucket: 'eprojectbabyshop.firebasestorage.app',
    measurementId: 'G-RF5MV85KC0',
  );
}
